/*Executive Analytics Questions */
-- EA-01: What is the total Assets Under Management (AUM) managed by Atlas Asset Management?
select sum(market_value) as total_aum
from atlas;

-- EA-02: How is AUM distributed across portfolio types?
select portfolio_type,sum(market_value) as total_aum
from atlas
group by portfolio_type
order by total_aum desc;

-- EA-03: Which investor segments contribute the highest market value?
SELECT investor_segment, SUM(market_value) AS total_market_value
FROM atlas
GROUP BY investor_segment
ORDER BY total_market_value DESC;

-- EA-04: What are the top 10 portfolios by market value?
select portfolio_id, sum(market_value) as portfolio_value
from atlas
group by portfolio_id
order by portfolio_value desc
limit 10;

-- EA-05: Which asset classes contribute the largest share of portfolio value?
select asset_class,sum(market_value) as total_market_value
from atlas
group by asset_class
order by total_market_value desc;

-- EA-06: Which sectors represent the largest investment exposure?
select sector,sum(market_value) as total_market_value
from atlas
group by sector
order by total_market_value desc;

-- EA-07: How much management fee revenue is generated by each portfolio type?
select portfolio_type, sum(management_fee_revenue) as total_fee_revenue
from atlas
group by portfolio_type
order by total_fee_revenue desc;

-- EA-08: What percentage of portfolios currently require rebalancing?
select rebalancing_needed,count(*) as portfolio_count,
round(count(*)*100/sum(count(*)) over(),2) as percentage_share 
from atlas
group by rebalancing_needed;

/*PORTFOLIO PERFORMANCE ANALYTICS */

-- PP01 — Average Annual Return by Portfolio Type

select portfolio_type,round(avg(monthly_return_pct),2) as avg_annual_return_pct
from atlas
group by portfolio_type
order by avg_annual_return_pct desc;

-- PP02 — Average Monthly Return by Asset Class
select asset_class,round(avg(monthly_return_pct),2) as avg_monthly_return_pct
from atlas
group by asset_class
order by avg_monthly_return_pct desc;

-- PP03 — Benchmark vs Portfolio Return
SELECT
    portfolio_type,
    ROUND(AVG(annual_return_pct), 2) AS avg_portfolio_return,
    ROUND(AVG(benchmark_return_pct), 2) AS avg_benchmark_return,
    ROUND(AVG(active_return_pct), 2) AS avg_active_return
FROM atlas
GROUP BY portfolio_type
ORDER BY avg_active_return DESC;

-- PP04 — Top 10 Portfolios by Annual Return
SELECT
    portfolio_id,
    portfolio_type,
    investor_segment,
    ROUND(annual_return_pct, 2) AS annual_return_pct,
    ROUND(benchmark_return_pct, 2) AS benchmark_return_pct,
    ROUND(active_return_pct, 2) AS active_return_pct
FROM atlas
ORDER BY annual_return_pct DESC
LIMIT 10;

-- PP05 — Top Alpha Generating Portfolios
SELECT
    portfolio_id,
    portfolio_type,
    asset_class,
    ROUND(alpha, 2) AS alpha,
    ROUND(annual_return_pct, 2) AS annual_return_pct
FROM atlas
ORDER BY alpha DESC
LIMIT 10;

-- PP06 — Best Risk-Adjusted Portfolios by Sharpe Ratio
SELECT
    portfolio_id,
    portfolio_type,
    asset_class,
    ROUND(sharpe_ratio, 2) AS sharpe_ratio,
    ROUND(volatility_pct, 2) AS volatility_pct,
    ROUND(annual_return_pct, 2) AS annual_return_pct
FROM atlas
ORDER BY sharpe_ratio DESC
LIMIT 10;

-- PP07 — Dividend Income by Asset Class
SELECT
    asset_class,
    ROUND(SUM(dividend_income), 2) AS total_dividend_income,
    ROUND(AVG(dividend_income), 2) AS avg_dividend_income
FROM atlas
GROUP BY asset_class
ORDER BY total_dividend_income DESC;

/* =====================================================
   RISK ANALYTICS
   ===================================================== */
   

-- RA01 – Average Volatility by Portfolio Type
SELECT
    portfolio_type,
    ROUND(AVG(volatility_pct),2) AS avg_volatility
FROM atlas
GROUP BY portfolio_type
ORDER BY avg_volatility DESC;

-- RA02 – Average Beta by Asset Class
SELECT
    asset_class,
    ROUND(AVG(beta),2) AS avg_beta
FROM atlas
GROUP BY asset_class
ORDER BY avg_beta DESC;

-- RA03 – Risk Distribution by Risk Level
SELECT
    risk_level,
    COUNT(*) AS holdings_count,
    ROUND(SUM(market_value),2) AS total_market_value
FROM atlas
GROUP BY risk_level
ORDER BY total_market_value DESC;

-- RA04 – Highest Risk Portfolios
SELECT
    portfolio_id,
    portfolio_type,
    ROUND(volatility_pct,2) AS volatility_pct
FROM atlas
ORDER BY volatility_pct DESC
LIMIT 10;

-- RA05 – Concentration Risk Analysis
SELECT
    portfolio_id,
    portfolio_type,
    ROUND(concentration_risk_score,2) AS concentration_risk_score
FROM atlas
ORDER BY concentration_risk_score DESC
LIMIT 10;

-- RA06 – Sharpe Ratio by Risk Level
SELECT
    risk_level,
    ROUND(AVG(sharpe_ratio),2) AS avg_sharpe_ratio
FROM atlas
GROUP BY risk_level
ORDER BY avg_sharpe_ratio DESC;

-- RA07 – Alpha vs Risk Profile
SELECT
    risk_level,
    ROUND(AVG(alpha),2) AS avg_alpha,
    ROUND(AVG(volatility_pct),2) AS avg_volatility
FROM atlas
GROUP BY risk_level
ORDER BY avg_alpha DESC;

/* =====================================================
   ASSET ALLOCATION ANALYTICS
   ===================================================== */
   
  --  AA01 – Asset Allocation by Asset Class
  SELECT asset_class,
    ROUND(SUM(market_value),2) AS total_market_value,
    ROUND(SUM(market_value) * 100.0 /SUM(SUM(market_value)) OVER(),2) AS allocation_pct
FROM atlas
GROUP BY asset_class
ORDER BY total_market_value DESC;

-- AA02 – Sector Allocation Analysis
SELECT
    sector,
    ROUND(SUM(market_value),2) AS total_market_value
FROM atlas
GROUP BY sector
ORDER BY total_market_value DESC;

-- AA03 – Geographic Allocation Analysis
SELECT
    country,
    ROUND(SUM(market_value),2) AS total_market_value
FROM atlas
GROUP BY country
ORDER BY total_market_value DESC;

-- AA04 – Portfolio Allocation Efficiency
SELECT
    portfolio_type,
    ROUND(AVG(portfolio_weight_pct),2) AS avg_portfolio_weight
FROM atlas
GROUP BY portfolio_type
ORDER BY avg_portfolio_weight DESC;

-- AA05 – ESG Allocation Analysis 
SELECT
    asset_class,
    ROUND(AVG(esg_score),2) AS avg_esg_score
FROM atlas
GROUP BY asset_class
ORDER BY avg_esg_score DESC;

/* =====================================================
   DIVERSIFICATION & REBALANCING ANALYTICS
   ===================================================== */
   
-- DR01 – Rebalancing Requirement Analysis
SELECT
    rebalancing_needed,
    COUNT(*) AS portfolio_count,
    ROUND(SUM(market_value),2) AS total_market_value
FROM atlas
GROUP BY rebalancing_needed;

-- DR02 – Diversification Effectiveness
SELECT
    portfolio_type,
    ROUND(AVG(concentration_risk_score),2) AS avg_concentration_risk
FROM atlas
GROUP BY portfolio_type
ORDER BY avg_concentration_risk DESC;

-- DR03 – Top Holdings Exposure Analysis
SELECT
    top_holding_flag,
    ROUND(SUM(market_value),2) AS total_market_value,
    COUNT(*) AS holdings_count
FROM atlas
GROUP BY top_holding_flag;